"""empty message

Revision ID: e0a4e17fb195
Revises: 
Create Date: 2024-02-25 23:42:35.492102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0a4e17fb195'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp_title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('exp_amount', sa.Float(), nullable=False))
        batch_op.alter_column('exp_created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('exp_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.drop_column('exp_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('exp_updated_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('exp_created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('exp_amount')
        batch_op.drop_column('exp_title')

    op.create_table('task',
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_created_on', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('task_id', name='task_pkey')
    )
    # ### end Alembic commands ###
